apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World!"
  favorite:
    {{- with .Values.favorite }}
    drink: {{ .drink | default (printf "%s-tea" (include "fullname" $ )) }}
    food: {{ .food | upper | quote  }}
    {{- if eq .drink "coffee"  }}
    mug: "true"
    {{- end  }}
    {{- end }}
    toppings: |-
      {{- range .Values.pizzaToppings }}
      - {{ . | title | quote }}
      {{- end }}
 
