apiVersion: v2
name: rttl-jupyterhub
description: A Helm chart for the University of Washington JupyterHubs for Teaching service

type: application

version: 0.4.0

dependencies:
  - name: jupyterhub
    version: "4.0.0"
    repository: "https://jupyterhub.github.io/helm-chart"
  - name: rttl-jh-nfs
    version: "0.0.4"
    condition: global.rttl.features.nfs.enabled

