ingress:
  enabled: true
  hosts:
    - rttl.axdd.s.uw.edu
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
hub:
  baseUrl: ""
  networkPolicy:
    enabled: true
  services:
    rttl_admin_service:
      name: rttl_admin_service
      admin: true
      apiToken: ""
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
  resources:
    requests:
      cpu: 150m
      memory: 512Mi
  config:
    Authenticator:
      admin_users:
        - replaceme
        - a_rttl_canvas_int
      allowed_users:
        - replaceme
        - a_rttl_canvas_int
    GenericOAuthenticator:
      client_id: ""
      client_secret: ""
      oauth_callback_url: ""
      authorize_url: https://canvas.uw.edu/login/oauth2/auth
      token_url: https://canvas.uw.edu/login/oauth2/token
      userdata_url: https://canvas.uw.edu/api/v1/users/self/profile
      scope:
        - url:GET|/api/v1/users/:user_id/profile
      username_key: login_id
    JupyterHub:
      authenticator_class: generic-oauth
proxy:
  secretToken:
  chp:
    networkPolicy:
      enabled: true
  service:
    type: ClusterIP
prePuller:
  continuous:
    enabled: false
  hook:
    enabled: false
  extraImages: {}
scheduling:
  userPlaceholder:
    enabled: false
    replicas: 0
  userPods:
    nodeAffinity:
      matchNodePurpose: require
    tolerations:
      - key: hub.jupyter.org/dedicated
        operator: Equal
        value: streamuser
        effect: NoSchedule
      - key: hub.jupyter.org_dedicated
        operator: Equal
        value: streamuser
        effect: NoSchedule
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
cull:
  enabled: true
  timeout: 1200
  every: 300
singleuser:
  image:
    name: us-west1-docker.pkg.dev/uwit-mci-axdd/rttl-images/jupyter-scipy-notebook
    tag: "2.3"
    pullPolicy: IfNotPresent
  storage:
    capacity: 5G
    dynamic:
      storageClass: standard-retain
  cpu:
    guarantee: 0.5
    limit: 2
  memory:
    guarantee: "1G"
    limit: "2G"
  networkPolicy:
    enabled: true
  startTimeout: 600
  defaultUrl: "/lab"
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "/bin/sh"
          - "-c"
          - >
            mkdir -p /home/jovyan/.ipython/profile_default;
            echo 'c.InteractiveShell.cache_size = 0' > /home/jovyan/.ipython/profile_default/ipython_kernel_config.py;
debug:
  enabled: false
