kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.rttl.pvstorageclass }}
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Namespace }}-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Release.Namespace }}.svc.cluster.local
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jupyterhub-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi